eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul


zuul:
#  #zuul默认为所有服务开启默认的路由，为了服务安全，此处关闭
#  ignored-services: *
  routes:
    api-user:
      path: /api-user/**
      serviceId: user-service
